import { AppColorsType } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const createChatDrawerStyles = (appColors: AppColorsType) =>
  StyleSheet.create({
    panel: {
      backgroundColor: appColors.bg.drawer,
      paddingTop: 18,
      paddingHorizontal: 12,
      paddingBottom: 14,
      borderRightWidth: 0,
      borderTopRightRadius: 20,
      borderBottomRightRadius: 20,
      shadowColor: appColors.shadow.base,
      shadowOpacity: 0.36,
      shadowRadius: 18,
      shadowOffset: { width: 4, height: 10 },
      elevation: 16,
    },
    logoImage: { height: 33, width: 33, borderRadius: 10 },
    hero: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 6,
      paddingVertical: 6,
      marginBottom: 8,
      gap: 5,
    },
    heroBadge: {
      width: 30,
      height: 30,
      borderRadius: 8,
      backgroundColor: appColors.bg.surface,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 8,
    },
    heroTextWrap: {
      flex: 1,
    },
    brandLabel: {
      color: appColors.text.muted,
      fontSize: 10,
      textTransform: "uppercase",
      letterSpacing: 0.6,
      fontWeight: "700",
    },
    title: {
      color: appColors.text.primary,
      fontSize: 16,
      fontWeight: "700",
    },
    subtitle: {
      color: appColors.text.muted,
      fontSize: 11,
      marginTop: 1,
    },
    closeButton: {
      width: 36,
      height: 36,
      borderRadius: 7,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.surface,
    },
    searchWrap: {
      minHeight: 42,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: appColors.border.drawerAction,
      backgroundColor: appColors.bg.surface,
      flexDirection: "row",
      alignItems: "center",
      paddingLeft: 8,
      paddingRight: 6,
      gap: 8,
      marginBottom: 8,
    },
    searchIconWrap: {
      width: 24,
      height: 24,
      borderRadius: 7,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.drawerAction,
    },
    searchInput: {
      flex: 1,
      color: appColors.text.primary,
      fontSize: 13,
      paddingVertical: 8,
    },
    searchClearButton: {
      width: 22,
      height: 22,
      borderRadius: 7,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.drawerAction,
    },
    bottomSectionCard: {
      marginTop: 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: appColors.border.drawerAction,
      backgroundColor: appColors.bg.surface,
      padding: 10,
    },
    settingsHeader: {
      marginBottom: 8,
      paddingHorizontal: 2,
    },
    settingsEyebrow: {
      color: appColors.text.weak,
      fontSize: 10,
      textTransform: "uppercase",
      letterSpacing: 0.6,
      fontWeight: "700",
    },
    settingsHeading: {
      color: appColors.text.primary,
      fontSize: 14,
      fontWeight: "700",
      marginTop: 2,
    },
    settingsHint: {
      color: appColors.text.muted,
      fontSize: 11,
      marginTop: 2,
      lineHeight: 16,
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 7,
      marginTop: 2,
    },
    sectionLabel: {
      color: appColors.text.muted,
      fontSize: 11,
      marginBottom: 0,
      paddingHorizontal: 2,
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: 0.55,
    },
    countChip: {
      minWidth: 24,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 8,
      paddingVertical: 1,
      backgroundColor: appColors.bg.drawerAction,
    },
    countText: {
      color: appColors.text.secondary,
      fontSize: 11,
      fontWeight: "700",
    },
    settingsButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: appColors.bg.drawerAction,
      borderColor: appColors.border.drawerAction,
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 12,
      minHeight: 48,
      paddingVertical: 10,
    },
    settingsIconWrap: {
      width: 26,
      height: 26,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.modelButton,
    },
    settingsText: {
      flex: 1,
      color: appColors.text.primary,
      fontSize: 13,
      fontWeight: "600",
    },
    settingsChevronWrap: {
      width: 24,
      height: 24,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.modelButton,
    },
    list: {
      flex: 1,
    },
    listContent: {
      paddingBottom: 14,
    },
    emptyState: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flexWrap: "wrap",
      paddingHorizontal: 10,
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: appColors.border.drawerAction,
      backgroundColor: appColors.bg.surface,
    },
    emptyText: {
      color: appColors.text.muted,
      fontSize: 12,
      fontWeight: "500",
    },
    chatRow: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 10,
      minHeight: 44,
      paddingVertical: 6,
      paddingLeft: 8,
      paddingRight: 6,
      marginBottom: 6,
      backgroundColor: "transparent",
    },
    chatRowMainButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      minHeight: 32,
      paddingRight: 4,
    },
    chatRowActive: {
      backgroundColor: appColors.bg.chatActive,
    },
    chatMain: {
      flex: 1,
    },
    chatIconWrap: {
      width: 24,
      height: 24,
      borderRadius: 7,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.surface,
      marginRight: 8,
    },
    chatIconWrapActive: {
      backgroundColor: appColors.bg.modelButton,
    },
    chatTitle: {
      color: appColors.text.primary,
      fontSize: 13,
      fontWeight: "500",
      marginBottom: 2,
    },
    chatPreview: {
      color: appColors.text.weak,
      fontSize: 11,
    },
    chatDeleteButton: {
      width: 30,
      height: 30,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.drawerAction,
      borderWidth: 1,
      borderColor: appColors.border.drawerAction,
    },
  });
