import { AppColorsType } from "@/constants/theme";
import { Platform, StyleSheet } from "react-native";

export const createIndexStyles = (appColors: AppColorsType) =>
  StyleSheet.create({
    screenContainer: {
      backgroundColor: appColors.bg.screen,
    },
    topOverlayGradient: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: 96,
      zIndex: 20,
      backgroundColor: "transparent",
    },
    topBar: {
      position: "absolute",
      top: 10,
      left: 12,
      right: 12,
      zIndex: 30,
      elevation: 2,
      minHeight: 44,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    modelDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    modelText: {
      color: appColors.text.secondary,
      fontSize: 13,
      fontWeight: "600",
      flexShrink: 1,
    },
    floatingPill: {
      borderRadius: 36,
      padding: 12,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 6,
      backgroundColor: appColors.bg.surface,
      borderWidth: 1,
      borderColor: appColors.border.subtle,
      shadowColor: appColors.shadow.base,
      shadowOpacity: 0.3,
      shadowRadius: 9,
      shadowOffset: { width: 0, height: 5 },
      elevation: 10,
    },
    newChatPillTouch: {
      borderRadius: 999,
      overflow: "hidden",
      shadowColor: appColors.shadow.base,
      shadowOpacity: 0.28,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 10,
    },
    newChatPill: {
      padding: 10,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 10,
    },
    floatingPillText: {
      color: appColors.text.secondary,
      fontSize: 13,
      fontWeight: "600",
    },
    list: {
      flex: 1,
      backgroundColor: appColors.bg.screen,
    },
    listContent: {
      paddingHorizontal: 14,
      paddingTop: 84,
    },
    emptyWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: 100,
      paddingHorizontal: 28,
    },
    logoBubble: {
      width: 54,
      height: 54,
      borderRadius: 27,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.surface,
      borderWidth: 1,
      borderColor: appColors.border.subtle,
      marginBottom: 14,
    },
    emptyTitle: {
      color: appColors.text.primary,
      fontSize: 24,
      fontWeight: "700",
      textAlign: "center",
      marginBottom: 8,
    },
    emptySubtext: {
      color: appColors.text.muted,
      fontSize: 14,
      textAlign: "center",
      lineHeight: 20,
    },
    assistantRow: {
      width: "100%",
      marginBottom: 16,
      flexDirection: "row",
      alignItems: "flex-start",
    },
    assistantAvatar: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: appColors.bg.bubbleAssistant,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 1,
      marginRight: 10,
    },
    assistantBody: {
      flex: 1,
      paddingTop: 1,
      paddingRight: 6,
    },
    messageContentWrap: {
      gap: 8,
    },
    assistantText: {
      color: appColors.text.secondary,
      fontSize: 16,
      lineHeight: 24,
    },
    cursor: {
      color: appColors.text.secondary,
      fontWeight: "700",
    },
    userRow: {
      width: "100%",
      alignItems: "flex-end",
      marginBottom: 14,
    },
    userBubble: {
      maxWidth: "86%",
      backgroundColor: appColors.bg.bubbleUser,
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: appColors.border.actionSecondary,
    },
    userAttachmentRow: {
      gap: 6,
      marginBottom: 8,
    },
    userAttachmentChip: {
      minHeight: 26,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: appColors.border.subtle,
      backgroundColor: appColors.bg.surface,
      paddingHorizontal: 8,
      paddingVertical: 4,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    userAttachmentText: {
      color: appColors.text.secondary,
      fontSize: 11,
      flexShrink: 1,
    },
    userText: {
      color: appColors.text.primary,
      fontSize: 15,
      lineHeight: 22,
    },
    codeBlock: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: appColors.border.chatRow,
      backgroundColor: appColors.bg.surfaceAlt,
      paddingTop: 28,
      paddingBottom: 10,
      paddingHorizontal: 10,
      position: "relative",
    },
    codeBlockLang: {
      position: "absolute",
      top: 8,
      left: 10,
      color: appColors.text.weak,
      fontSize: 10,
      letterSpacing: 0.5,
      fontWeight: "700",
    },
    codeCopyButton: {
      position: "absolute",
      top: 6,
      right: 6,
      zIndex: 2,
      width: 24,
      height: 24,
      borderRadius: 7,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.surface,
      borderWidth: 1,
      borderColor: appColors.border.subtle,
    },
    codeBlockText: {
      color: appColors.text.secondary,
      fontSize: 13,
      lineHeight: 20,
      fontFamily: Platform.select({
        ios: "Menlo",
        android: "monospace",
        default: "monospace",
      }),
    },
    userActionsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginTop: 6,
      marginRight: 4,
    },
    assistantActionsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginTop: 6,
    },
    messageAction: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingVertical: 2,
    },
    messageActionDisabled: {
      opacity: 0.4,
    },
    messageActionText: {
      color: appColors.text.weak,
      fontSize: 12,
      fontWeight: "500",
    },
    thinkingBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 16,
      paddingBottom: 6,
      backgroundColor: appColors.bg.screen,
    },
    thinkingText: {
      color: appColors.text.muted,
      fontSize: 12,
    },
    composerWrap: {
      paddingHorizontal: 10,
      paddingTop: 8,
      paddingBottom: 10,
      borderTopWidth: 1,
      borderTopColor: appColors.border.default,
      backgroundColor: appColors.bg.screen,
    },
    composerInner: {
      flexDirection: "row",
      alignItems: "flex-end",
      borderRadius: 22,
      backgroundColor: appColors.bg.input,
      borderWidth: 1,
      borderColor: appColors.border.input,
      paddingLeft: 12,
      paddingRight: 8,
      paddingVertical: 8,
    },
    composerInputWrap: {
      flex: 1,
      minHeight: 24,
      maxHeight: 180,
      justifyContent: "center",
    },
    attachButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: 8,
      backgroundColor: appColors.bg.actionSecondary,
    },
    chooseModelButton: {
      minHeight: 56,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: appColors.border.input,
      backgroundColor: appColors.bg.input,
      paddingHorizontal: 12,
      paddingVertical: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    chooseModelLeft: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    chooseModelIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 9,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.drawerAction,
      borderWidth: 1,
      borderColor: appColors.border.drawerAction,
    },
    chooseModelTextWrap: {
      flex: 1,
    },
    chooseModelTitle: {
      color: appColors.text.secondary,
      fontWeight: "700",
    },
    chooseModelSubtitle: {
      color: appColors.text.muted,
      marginTop: 1,
    },
    input: {
      width: "100%",
      color: appColors.text.primary,
      fontSize: 16,
      lineHeight: 22,
      minHeight: 24,
      maxHeight: 110,
      paddingTop: 6,
      paddingBottom: 6,
      paddingRight: 10,
    },
    webSearchButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: 8,
      backgroundColor: appColors.bg.actionSecondary,
    },
    webSearchButtonActive: {
      backgroundColor: appColors.bg.success,
    },
    sendButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: 8,
    },
    sendButtonEnabled: {
      backgroundColor: appColors.bg.success,
    },
    sendButtonDisabled: {
      backgroundColor: appColors.bg.actionSecondary,
    },
    stopButton: {
      backgroundColor: appColors.bg.stop,
    },
    pdfAttachmentRow: {
      marginBottom: 8,
      alignSelf: "flex-start",
      width: "100%",
      height: 72,
      maxHeight: 72,
      overflow: "hidden",
    },
    pdfAttachmentList: {
      height: 72,
      maxHeight: 72,
    },
    pdfAttachmentListContent: {
      gap: 8,
      paddingRight: 6,
    },
    pdfAttachmentChip: {
      width: 72,
      height: 72,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: appColors.border.chatRow,
      backgroundColor: appColors.bg.surfaceAlt,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 6,
      paddingVertical: 6,
      position: "relative",
    },
    pdfAttachmentName: {
      maxWidth: 58,
      color: appColors.text.secondary,
      fontSize: 9,
      marginTop: 4,
      textAlign: "center",
    },
    pdfAttachmentStatus: {
      color: appColors.text.weak,
      fontSize: 8,
      marginTop: 1,
    },
    pdfAttachmentRemove: {
      width: 18,
      height: 18,
      borderRadius: 9,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.surface,
      borderWidth: 1,
      borderColor: appColors.border.subtle,
      position: "absolute",
      top: 4,
      right: 4,
    },
    sourceModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: appColors.overlay.dim,
    },
    sourceModalWrap: {
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: 16,
      paddingVertical: 24,
    },
    sourceModalCard: {
      maxHeight: "72%",
      borderRadius: 16,
      borderWidth: 1,
      borderColor: appColors.border.chatRow,
      backgroundColor: appColors.bg.surface,
      overflow: "hidden",
    },
    sourceModalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderBottomWidth: 1,
      borderBottomColor: appColors.border.chatRow,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    sourceModalTitle: {
      color: appColors.text.primary,
      fontWeight: "700",
      fontSize: 16,
    },
    sourceModalCloseButton: {
      width: 30,
      height: 30,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.surfaceAlt,
      borderWidth: 1,
      borderColor: appColors.border.subtle,
    },
    sourceListContent: {
      padding: 10,
      gap: 8,
    },
    sourceItemRow: {
      minHeight: 52,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: appColors.border.chatRow,
      backgroundColor: appColors.bg.surfaceAlt,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 10,
      gap: 10,
    },
    sourceItemLeft: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    sourceItemIconWrap: {
      width: 28,
      height: 28,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.surface,
      borderWidth: 1,
      borderColor: appColors.border.subtle,
    },
    sourceItemFavicon: {
      width: 14,
      height: 14,
      borderRadius: 7,
    },
    sourceItemTextWrap: {
      flex: 1,
    },
    sourceItemTitle: {
      color: appColors.text.primary,
      fontSize: 13,
      fontWeight: "600",
    },
    sourceItemUrl: {
      color: appColors.text.weak,
      fontSize: 11,
      marginTop: 1,
    },
    drawerRoot: {
      flex: 1,
    },
    drawerBackdropLayer: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: appColors.overlay.dim,
    },
    drawerBackdropTouch: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    drawerPanel: {
      position: "absolute",
      left: 0,
      top: 18,
      bottom: 18,
      width: "82%",
      maxWidth: 360,
      backgroundColor: appColors.bg.drawer,
      paddingTop: 20,
      paddingHorizontal: 12,
      paddingBottom: 16,
      borderRightWidth: 1,
      borderRightColor: appColors.border.drawerRight,
      borderTopRightRadius: 18,
      borderBottomRightRadius: 18,
      shadowColor: appColors.shadow.base,
      shadowOpacity: 0.3,
      shadowRadius: 14,
      shadowOffset: { width: 2, height: 8 },
      elevation: 14,
    },
    drawerHero: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: appColors.bg.surfaceAlt,
      borderWidth: 1,
      borderColor: appColors.border.chatRow,
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 10,
      marginBottom: 12,
    },
    drawerHeroBadge: {
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: appColors.bg.surface,
      borderWidth: 1,
      borderColor: appColors.border.subtle,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 10,
    },
    drawerHeroTextWrap: {
      flex: 1,
    },
    drawerTitle: {
      color: appColors.text.primary,
      fontSize: 17,
      fontWeight: "700",
    },
    drawerSubtitle: {
      color: appColors.text.muted,
      fontSize: 12,
      marginTop: 1,
    },
    drawerClose: {
      width: 30,
      height: 30,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: appColors.bg.drawerAction,
    },
    newChatButtonTouch: {
      borderRadius: 12,
      overflow: "hidden",
      marginBottom: 14,
    },
    newChatButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: appColors.bg.modelButton,
      borderColor: appColors.border.drawerAction,
      borderWidth: 1,
      borderRadius: 12,
      paddingVertical: 10,
    },
    newChatText: {
      color: appColors.text.secondary,
      fontSize: 14,
      fontWeight: "600",
    },
    drawerSection: {
      marginBottom: 14,
    },
    drawerSectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    drawerSectionLabel: {
      color: appColors.text.muted,
      fontSize: 12,
      marginBottom: 8,
      paddingHorizontal: 2,
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    drawerCountChip: {
      minWidth: 24,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 8,
      paddingVertical: 2,
      backgroundColor: appColors.bg.surface,
      borderWidth: 1,
      borderColor: appColors.border.subtle,
    },
    drawerCountText: {
      color: appColors.text.secondary,
      fontSize: 11,
      fontWeight: "700",
    },
    modelDrawerButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: appColors.bg.surfaceAlt,
      borderColor: appColors.border.modelButton,
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    modelDrawerText: {
      flex: 1,
      color: appColors.text.secondary,
      fontSize: 14,
      fontWeight: "600",
    },
    drawerList: {
      flex: 1,
    },
    drawerListContent: {
      paddingBottom: 8,
    },
    drawerEmptyState: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 10,
      paddingVertical: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: appColors.border.chatRow,
      backgroundColor: appColors.bg.surfaceAlt,
    },
    drawerEmptyText: {
      color: appColors.text.muted,
      fontSize: 12,
      fontWeight: "500",
    },
    chatRow: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 12,
      paddingLeft: 12,
      paddingRight: 10,
      paddingVertical: 10,
      marginBottom: 8,
      backgroundColor: appColors.bg.surfaceAlt,
      borderWidth: 1,
      borderColor: appColors.border.chatRow,
    },
    chatRowActive: {
      backgroundColor: appColors.bg.chatActive,
      borderColor: appColors.border.chatRowActive,
    },
    chatActiveMarker: {
      width: 3,
      alignSelf: "stretch",
      borderRadius: 999,
      backgroundColor: appColors.bg.success,
      marginRight: 10,
    },
    chatMain: {
      flex: 1,
    },
    chatTitle: {
      color: appColors.text.primary,
      fontSize: 14,
      fontWeight: "600",
      marginBottom: 2,
    },
    chatPreview: {
      color: appColors.text.muted,
      fontSize: 12,
    },
  });
